# Generated by Django 3.1.3 on 2021-05-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210526_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='choice',
            new_name='choices',
        ),
    ]
